### ISSUE TITLE
Set up Continuous integration with GitHub Actions

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#10]

**Comment by thesohelshaikh** [comment]
Can you please add elaborate on this? I would like to take this up.

**Comment by waseefakhtar** [comment]
> Can you please add elaborate on this? I would like to take this up.

I added the file here: https://github.com/waseefakhtar/dose-android/blob/main/.github/workflows/android.yml

1. It currently builds the project (https://github.com/waseefakhtar/dose-android/commit/f8c175b66b2b2853fb5f2b4de072a7d506ce55d1)
2. Archives the built app (https://github.com/waseefakhtar/dose-android/pull/21)

Here are the remaining things I'd like to set up before closing this issue:
1. Run tests (Perhaps you can take this up)
2. Run ktlint (Not added to the project yet https://github.com/waseefakhtar/dose-android/issues/23, so we can wait a bit for that)
