### ISSUE TITLE
Support to Gradle Version Catalog

### ISSUE THREAD

**Issue by Wottrich** [waseefakhtar/dose-android#101]
# Context

Creating a issue to work on implementation of Gradle Version Catalog in the project!

# Proposal

Follow documentation:

https://developer.android.com/build/migrate-to-catalogs

**Comment by Wottrich** [comment]
Hey @waseefakhtar, can you assign this issue to me? I'm already doing this migration :D

**Comment by waseefakhtar** [comment]
> Hey @waseefakhtar, could you assign this issue to me? I'm already doing this migration :D

Sure, go ahead! :)
