### ISSUE TITLE
Migrate all Gradle files from Groovy to Kotlin and enhance the existing ones.

### ISSUE THREAD

**Issue by ankur141295** [waseefakhtar/dose-android#121]
Hi @waseefakhtar , 
 
I've observed that the Module-level Gradle file has already been migrated from Groovy to Kotlin. To maintain consistency, it would be beneficial to migrate the Project-level and Settings Gradle files from Groovy to Kotlin as well.

Furthermore, we can further enhance the Module-level Gradle file by moving certain elements to the libs.version.toml file. This includes:
-  minSdk
-  targetSdk
-  top-level plugins

This approach would improve the overall organization and readability of the Gradle configuration.

Please let me know if you have any questions or concerns regarding this proposal.

**Comment by waseefakhtar** [comment]
Totally! Would love that consistency across the project.
