### ISSUE TITLE
Fix Weird screen crop at AddMedicationScreen

### ISSUE THREAD

**Issue by ipirangad3v** [waseefakhtar/dose-android#19]
the top and bottom of AddMedicationScreen is showing a weird behavior.

![Screenshot_1658687552](https://user-images.githubusercontent.com/17752700/180661181-d807a8cb-215a-4fef-b1fc-0fe2ff9c026e.png)

**Comment by AnthoniIP** [comment]
@waseefakhtar hi, i just did this fix and PR the branch for you, i hope this may be useful for you, love the project and a hope help much more.

**Comment by AnthoniIP** [comment]
@waseefakhtar hi, i just did this fix and PR the branch for you, i hope this may be useful for you, love the project and a hope help much more.

**Comment by waseefakhtar** [comment]
> @waseefakhtar hi, i just did this fix and PR the branch for you, i hope this may be useful for you, love the project and a hope help much more.

Thank you! Just reviewed it and left some comments.
