### ISSUE TITLE
Implement ViewModel layer

### ISSUE THREAD

**Issue by DigiDevZ** [waseefakhtar/dose-android#28]
Hi, I noticed that there is commented code for where ViewModels would be passed in through out the codebase. I would like to contribute and implement this layer for the project.  

I will update this issue with whatever I work on and make sure the implementation is agreed upon with the PR.

**Comment by waseefakhtar** [comment]
Thanks for taking the initiative! I've now reviewed your PR and left some comments.

**Comment by DigiDevZ** [comment]
Awesome thanks for the feedback! I will get to the PR comments towards the end of this week

**Comment by waseefakhtar** [comment]
> Awesome thanks for the feedback! I will get to the PR comments towards the end of this week

@DigiDevZ any update regarding this? 🙂

**Comment by DigiDevZ** [comment]
Yes, my apologies I had some life events come up that prevented me from getting to this when I originally planned. I saw that you had incorporated most of the ViewModel implementations already into the main branch so I went ahead and pulled that into my fork/branch, rebased and fixed merge conflicts, and added in the suggestions from the PR comments.
