### ISSUE TITLE
Show a success message (use Toast or Snackbar) when new Medication is added to DB succesfully.

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#31]
You can start by looking into the DB insertion flow from `MedicationConfirmScreen`.

**Comment by shivam-gupta007** [comment]
Hey @waseefakhtar, I would love to work on this issue.

**Comment by waseefakhtar** [comment]
> Hey @waseefakhtar, I would love to work on this issue.

Sure, @shivam-gupta007!

**Comment by alviandf** [comment]
Hi @waseefakhtar, can I work on this issue?

**Comment by waseefakhtar** [comment]
> Hi @waseefakhtar, can I work on this issue?

Sure, @alviandf! Go for it! 💪

**Comment by alviandf** [comment]
Hi @waseefakhtar I have done PR for this issue
