### ISSUE TITLE
Show "time remaining" for each medication

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#40]

**Comment by sravank9** [comment]
Hi @waseefakhtar, Please assign this to me, if this issue is still open

**Comment by waseefakhtar** [comment]
> Hi @waseefakhtar, Please assign this to me, if this issue is still open

Done! :)

**Comment by sravank9** [comment]
@waseefakhtar 

Will pick this up
Once this P.R got merged
https://github.com/waseefakhtar/dose-android/issues/30

**Comment by sravank9** [comment]
@waseefakhtar 

Raised a P.R. for this
Please review.
