### ISSUE TITLE
Avoid navigating back to MedicationConfirm screen from HomeScreen after medications are added

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#65]

**Comment by Kayvee08** [comment]
Hi @waseefakhtar , I've fixed this issue and shared the PR. 
I liked your project and hope to contribute more.

**Comment by waseefakhtar** [comment]
> Hi @waseefakhtar , I've fixed this issue and shared the PR. I liked your project and hope to contribute more.

Thank you for your contribution @Kayvee08! I've now reviewed your PR and left a comment. :)

**Comment by waseefakhtar** [comment]
Resolved in #72
