### ISSUE TITLE
Replace Toasts with bottom sheet that appears for 3 secs

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#71]

**Comment by MJJacobs01** [comment]
Can it be a snack bar opposed to a bottom sheet?

**Comment by Wottrich** [comment]
I like the idea to use snackbar too, bottom sheet could be very intrusive to the user

**Comment by Ammar-Ishfaq** [comment]
Yes, I also like the idea of a snack bar.
can I start work on it? @waseefakhtar

**Comment by waseefakhtar** [comment]
I agree with everyone. Snackbar sounds better! Feel free to work on it. :)

**Comment by Ammar-Ishfaq** [comment]
Hi @waseefakhtar, I wanted to let you know that I've submitted PR #97  for the Snackbar functionality. Would you mind taking a look and considering merging it when you have a moment? Thank you! 😊
