### ISSUE TITLE
A big name medication hide "Take now" button from Home screen

### ISSUE THREAD

**Issue by Wottrich** [waseefakhtar/dose-android#75]
# Context
When I created a medication with a big name the button just gone from Home and I can't click to take the medication

# Video

https://github.com/waseefakhtar/dose-android/assets/24254062/f1f54089-3158-456d-a408-a7f19701f54c

**Comment by Wottrich** [comment]
I am very interested in making this issue to contribute to the project!

**Comment by waseefakhtar** [comment]
Good catch @Wottrich! Feel free to contribute :)
