### ISSUE TITLE
Make Medication Name field active after navigating to AddMedication

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#79]

**Comment by MJJacobs01** [comment]
Good evening,

Can I get involved with this one?

**Comment by waseefakhtar** [comment]
> Good evening,
> 
> Can I get involved with this one?

Sure, go ahead!

**Comment by MJJacobs01** [comment]
To make sure that I understand the issue correctly.

When navigating to add medication screen the focus should already be on medication name?

**Comment by waseefakhtar** [comment]
> To make sure that I understand the issue correctly.
> 
> When navigating to add medication screen the focus should already be on medication name?

The idea is that when the AddMedication screen is shown, the Medication Name text field should get active and the keyboard should show up automatically so user is saved from tapping on the text field first.

**Comment by MJJacobs01** [comment]
Okay, I am done with that.  May I also update the Kotlin syntax in the same file?

**Comment by MJJacobs01** [comment]
Thanks.  Pull request to follow shortly.  Thanks for allowing me to contribute

**Comment by MJJacobs01** [comment]
Thanks a lot.
