### ISSUE TITLE
Replace DatePicker with Material3 DatePicker

### ISSUE THREAD

**Issue by waseefakhtar** [waseefakhtar/dose-android#86]
https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#DatePicker(androidx.compose.material3.DatePickerState,androidx.compose.ui.Modifier,androidx.compose.material3.DatePickerFormatter,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.material3.DatePickerColors)

**Comment by MJJacobs01** [comment]
Good evening,

Can I work on this one?

**Comment by waseefakhtar** [comment]
> Good evening,
> 
> Can I work on this one?

Hey. Sure, go ahead!
